# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 001c8afd67d68005b993d9af362c305a65c9b25fff652bfaf8023bf0fe805af6ed261650f154fcf19399dcb37f54253fbdaa10fdf53347a059ee014e9df377df
  facebook_app_id: 125068118079347
  facebook_app_secret: 8297c387919c4b1d0bd7ff1e462071cd

  twitter_app_id: GUMqDkguFmNIUx9hPrxRZJkjX
  twitter_app_secret: i4yTG68SrETYxptBq8a9cTcEzOkujorgMZiXpsw9CgnGQKORw8

test:
  secret_key_base: fa67465baa7f4f7338f2bbc487f540c1624d107d289ff636742b95bf6c1cef4f61f49e2ebe4632779fe0593728cd2e87e9adfddd633bb7b0c1c77d11bc4aed47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
